[build]
  command = "node generate-config.js"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["guides/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
